// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: protos/messaging.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HabCommand_CommandType int32

const (
	HabCommand_UNKNOWN     HabCommand_CommandType = 0
	HabCommand_LIST_THINGS HabCommand_CommandType = 1
)

// Enum value maps for HabCommand_CommandType.
var (
	HabCommand_CommandType_name = map[int32]string{
		0: "UNKNOWN",
		1: "LIST_THINGS",
	}
	HabCommand_CommandType_value = map[string]int32{
		"UNKNOWN":     0,
		"LIST_THINGS": 1,
	}
)

func (x HabCommand_CommandType) Enum() *HabCommand_CommandType {
	p := new(HabCommand_CommandType)
	*p = x
	return p
}

func (x HabCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HabCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_messaging_proto_enumTypes[0].Descriptor()
}

func (HabCommand_CommandType) Type() protoreflect.EnumType {
	return &file_protos_messaging_proto_enumTypes[0]
}

func (x HabCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HabCommand_CommandType.Descriptor instead.
func (HabCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_protos_messaging_proto_rawDescGZIP(), []int{0, 0}
}

type HabCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Request     *HTTPRequest           `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	CommandType HabCommand_CommandType `protobuf:"varint,3,opt,name=command_type,json=commandType,proto3,enum=HabCommand_CommandType" json:"command_type,omitempty"`
}

func (x *HabCommand) Reset() {
	*x = HabCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messaging_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HabCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HabCommand) ProtoMessage() {}

func (x *HabCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messaging_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HabCommand.ProtoReflect.Descriptor instead.
func (*HabCommand) Descriptor() ([]byte, []int) {
	return file_protos_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *HabCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HabCommand) GetRequest() *HTTPRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *HabCommand) GetCommandType() HabCommand_CommandType {
	if x != nil {
		return x.CommandType
	}
	return HabCommand_UNKNOWN
}

type HTTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messaging_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messaging_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_protos_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *HTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OnPremHabCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string      `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	HabCommand  *HabCommand `protobuf:"bytes,2,opt,name=hab_command,json=habCommand,proto3" json:"hab_command,omitempty"`
	Response    []byte      `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *OnPremHabCommandResponse) Reset() {
	*x = OnPremHabCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messaging_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnPremHabCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPremHabCommandResponse) ProtoMessage() {}

func (x *OnPremHabCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messaging_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPremHabCommandResponse.ProtoReflect.Descriptor instead.
func (*OnPremHabCommandResponse) Descriptor() ([]byte, []int) {
	return file_protos_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *OnPremHabCommandResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OnPremHabCommandResponse) GetHabCommand() *HabCommand {
	if x != nil {
		return x.HabCommand
	}
	return nil
}

func (x *OnPremHabCommandResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type OnPremError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *OnPremError) Reset() {
	*x = OnPremError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messaging_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnPremError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPremError) ProtoMessage() {}

func (x *OnPremError) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messaging_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPremError.ProtoReflect.Descriptor instead.
func (*OnPremError) Descriptor() ([]byte, []int) {
	return file_protos_messaging_proto_rawDescGZIP(), []int{3}
}

func (x *OnPremError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_protos_messaging_proto protoreflect.FileDescriptor

var file_protos_messaging_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x0a, 0x48, 0x61, 0x62,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x48, 0x54, 0x54,
	0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3a, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x48, 0x61, 0x62, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a,
	0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x49, 0x53,
	0x54, 0x5f, 0x54, 0x48, 0x49, 0x4e, 0x47, 0x53, 0x10, 0x01, 0x22, 0x39, 0x0a, 0x0b, 0x48, 0x54,
	0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x86, 0x01, 0x0a, 0x18, 0x4f, 0x6e, 0x50, 0x72, 0x65, 0x6d,
	0x48, 0x61, 0x62, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x0b, 0x68, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x48, 0x61, 0x62, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x0a, 0x68, 0x61, 0x62, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x32,
	0x0a, 0x0b, 0x4f, 0x6e, 0x50, 0x72, 0x65, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x23, 0x0a,
	0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_messaging_proto_rawDescOnce sync.Once
	file_protos_messaging_proto_rawDescData = file_protos_messaging_proto_rawDesc
)

func file_protos_messaging_proto_rawDescGZIP() []byte {
	file_protos_messaging_proto_rawDescOnce.Do(func() {
		file_protos_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_messaging_proto_rawDescData)
	})
	return file_protos_messaging_proto_rawDescData
}

var file_protos_messaging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_messaging_proto_goTypes = []interface{}{
	(HabCommand_CommandType)(0),      // 0: HabCommand.CommandType
	(*HabCommand)(nil),               // 1: HabCommand
	(*HTTPRequest)(nil),              // 2: HTTPRequest
	(*OnPremHabCommandResponse)(nil), // 3: OnPremHabCommandResponse
	(*OnPremError)(nil),              // 4: OnPremError
}
var file_protos_messaging_proto_depIdxs = []int32{
	2, // 0: HabCommand.request:type_name -> HTTPRequest
	0, // 1: HabCommand.command_type:type_name -> HabCommand.CommandType
	1, // 2: OnPremHabCommandResponse.hab_command:type_name -> HabCommand
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_messaging_proto_init() }
func file_protos_messaging_proto_init() {
	if File_protos_messaging_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_messaging_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HabCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messaging_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messaging_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnPremHabCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messaging_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnPremError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_messaging_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_messaging_proto_goTypes,
		DependencyIndexes: file_protos_messaging_proto_depIdxs,
		EnumInfos:         file_protos_messaging_proto_enumTypes,
		MessageInfos:      file_protos_messaging_proto_msgTypes,
	}.Build()
	File_protos_messaging_proto = out.File
	file_protos_messaging_proto_rawDesc = nil
	file_protos_messaging_proto_goTypes = nil
	file_protos_messaging_proto_depIdxs = nil
}
