type DeviceT = {
    id: string,
    propertyId: string,
    unitId: string | null,
    habThing: {
        configuration: {
            usercode_code_1: string,
            usercode_code_2: string,
            usercode_code_3: string,
            usercode_code_4: string,
            usercode_code_5: string,
            usercode_code_6: string,
            usercode_code_7: string,
            usercode_code_8: string,
            usercode_code_9: string,
            usercode_code_10: string,
            usercode_code_11: string,
            usercode_code_12: string,
            usercode_code_13: string,
            usercode_code_14: string,
            usercode_code_15: string,
            usercode_code_16: string,
            usercode_code_17: string,
            usercode_code_18: string,
            usercode_code_19: string,
            usercode_code_20: string,
            usercode_code_21: string,
            usercode_code_22: string,
            usercode_code_23: string,
            usercode_code_24: string,
            usercode_code_25: string,
            usercode_code_26: string,
            usercode_code_27: string,
            usercode_code_28: string,
            usercode_code_29: string,
            usercode_code_30: string,
        },
        label: string,
        statusInfo: {
            status: string,
            statusDetail: string,
        },
        uid: string,
    },
    lastRefreshedAt: string,
    lastWentOfflineAt: string | null,
}

type UnitT = {
    id: string,
    name: string,
    propertyId: string,
    calendarUrl: string,
    updatedBy: string,
}